name: CI

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run editorconfig-checker
        run: docker run --rm --volume="${{ github.workspace }}:/check" mstruebing/editorconfig-checker:latest
